### ISSUE TITLE
Consider using Borrow instead of AsRef

### ISSUE THREAD

**Issue by kballard** [gobanos/cargo-aoc#19]
I'm still not entirely certain when to use `Borrow` and when to use `AsRef`, but it appears that there's a blank `impl Borrow<T> for T` but there's no equivalent blanket impl for `AsRef`.

The motivation here is being able to write something like

```rust
struct Graph { … }

#[aoc_generator(day2)]
fn input_generator(input: &str) -> Graph { … }

#[aoc(day2, part1)]
fn part1(input: &Graph) -> usize { … }
```

Since `cargo-aoc` uses `AsRef`, this doesn't work as there's no `impl AsRef<Graph> for Graph`. If it used `Borrow` then the blanket impl would make this work.

This would not be a backwards-compatible change, as there exists `AsRef` impls that convert between `str` and `[u8]` but there's no equivalent `Borrow` impl. That said, it seems unexpected that someone would have a generator that produces e.g. a `String` and a corresponding solver that expects a `&[u8]`.

**Comment by kballard** [comment]
Right now when I write generators like this I end up having to return e.g. `Box<Graph>` instead, and this unnecessary boxing annoys me.

**Comment by gobanos** [comment]
The difference between `Borrow` & `AsRef` is really thin, and even [in the doc](https://doc.rust-lang.org/std/convert/trait.AsRef.html) this is unclear : 
> The key difference between the two traits is the intention:
> - Use `AsRef` when the goal is to simply convert into a reference
> - Use `Borrow` when the goal is related to writing code that is agnostic to the type of borrow and whether it is a reference or value

Based on this distinction, `AsRef` should be the right choice, but there is no `impl<T: ?Sized> AsRef<T> for T` (it conflicts with `impl<T: ?Sized, U: ?Sized> AsRef<U> for &T where T: AsRef<U>`...).

That said, the main use case of `AsRef` in `cargo-aoc` is to get raw input as a `&[u8]`, which I should be able to handle as a special case and use `Borrow` in the general case.

As anyone a different usage of `AsRef` ?

**Comment by kballard** [comment]
Yeah, I wish the docs did a better job explaining it. The first sentence of the `AsRef` docs I think is a more accurate description:

> A cheap reference-to-reference conversion.

`AsRef` is good for when you have a reference of one kind and want a reference of a different kind. Or if you have a smart pointer and want a reference. So you can use it to go from `&str` to `&[u8]`, or from `String` to `&str`, or even from `String` to `&[u8]`. But it won't work for arbitrary values.

`Borrow` meanwhile is a more general "you have some T and want to borrow it". This converts any input into a reference.

So the difference are:

- `AsRef` can convert between referenced types, e.g. `&str` -> `&[u8]`, but can't convert arbitrary values into references.
- `Borrow` can convert arbitrary values into references, but can't convert between referenced types.

So if your goal is "give me something that I can interpret as a `&[u8]`" then `AsRef` makes more sense, as I can supply a `&str` or `String` as that has a cheap conversion to `&[u8]`. But if your goal is "convert something to a reference" then you want `Borrow`.

Given all this, it seems clear that, from the perspective of a user of `cargo-aoc`, we want `Borrow` as it means I can return any type from my generator and consume it as a reference.

In an ideal world you'd be able to actually chain `AsRef` and `Borrow` together, to handle the scenario of "I want to convert something to a reference of a particular type", but since a type can implement `Borrow` multiple times I suspect you'd end up with an ambiguity error if you chain them together without specifying the intermediate type.

**Comment by TheDan64** [comment]
> Borrow can convert arbitrary values into references, but can't convert between referenced types.

Does this mean `Borrow` will give you a `&Vec<_>` instead of a `&[_]`?

I'm not familiar with the internals of this project, but would it be possible to define which borrowing approach to take in the `aoc` proc macro definition? That way you could specify `Borrow`, `AsRef`, or even `BorrowMut`, `AsMut`, etc (with `AsRef` being a default as it is today).

IE `#[aoc(day2, part1, AsRef)]`. This would allow for much greater flexibility

**Comment by gobanos** [comment]
Version 0.2.1 in now published, using `Borrow` instead of `AsRef`.

Update your `Cargo.toml`:
```
aoc-runner = "0.2.1"
aoc-runner-derive = "0.2.1"
```
and `cargo-aoc` : `$ cargo install cargo-aoc --force`

> Does this mean `Borrow` will give you a `&Vec<_>` instead of a `&[_]`?

There is a `impl<T> Borrow<[T]> for Vec<T>`, so you can still use slice as input for runners ;)

It should be possible to expose desired trait in the meta, but I prefer ergonomics over flexibility for this kind of really specific utilities projects, for the same reason, I've chosen to identify `Result` & `Option` in return position over adding info in the meta.

For mutability, I still don't know what to do, it will not play well with benchmarking, which is basically running the same function multiple time (without re-generating the input).

**Comment by kballard** [comment]
Without mutability, `cargo-aoc` could also just run the generator once and provide it to both parts of the day (with mutability, you wouldn't want to do that because then running both parts vs just running part2 would have different results).

I actually assumed that's what it did already, but I just realized that the `cargo aoc` output lists the generator time for both parts, which implies it's re-running the generator for each part.
