### ISSUE TITLE
Suggestion: Run all benchmarks

### ISSUE THREAD

**Issue by ThomasdenH** [gobanos/cargo-aoc#28]
Maybe add a flag to run all days and parts, for example for CI?

Something like `cargo aoc --all` and `cargo aoc bench --all`.

**Comment by AlisCode** [comment]
Hi Thomas, 

Running `cargo run` at the root of the project instead of  `cargo aoc` runs all the implemented days & parts if you have set your `main.rs` up as shown in the docs. This is what one should use in a CI environment IMO. 

You're right though, we should add a note about it in the docs.

Benching is something different, sadly I have never used Criterion myself so I can't be of any help here. I think that it requires a bit of setup code-wise. Maybe @gobanos knows a bit more about setting this up.

**Comment by ThomasdenH** [comment]
Super, it looks like `aoc_main!` is what I wanted. I'll edit the issue for benchmarks.
